allowBuilds:
  canvas: false
minimumReleaseAgeExclude:
  - vite@8.2.1
  - '@vitejs/plugin-react@6.1.0'
  - '@tanstack/query-core@5.102.4 || 5.102.5 || 5.102.8'
  - '@tanstack/react-query@5.102.4 || 5.102.5 || 5.102.8'
